name: Service Build

on:
  workflow_run:
    workflows:
      - ECR Repository

jobs:
  success:
    name: Test, Build, Push Container
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The first workflow completed successfully and run second workflow"

  failure:
    name: ECR Deployment Failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "ECR workflow failed"