name: Service Build

on:
  workflow_run:
    workflows:
      - ECR Repository
    types:
      - completed

jobs:
  success:
    name: Test, Build, Push Container
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The first workflow completed successfully and run second workflow"

  failure:
    name: ECR Deployment Failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "ECR workflow failed"

  workflow-status:
    if: always()
    name: Echo Workflow Status
    runs-on: ubuntu-latest
    needs:
      - success
      - failure
    steps:
      - name: Workflow Conclusion Action
        uses: technote-space/workflow-conclusion-action@v2.0.1

      - run: echo "${{ env.WORKFLOW_CONCLUSION }}"