name: Service Build

on:
  workflow_run:
    workflows:
      - ECR Repository
    types:
      - completed

jobs:
  success:
    name: Test, Build, Push Container
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Build success"

      - run: exit 1

  workflow-status:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Echo Workflow Status
    runs-on: ubuntu-latest
    needs:
      - success
    steps:
      - name: Workflow Conclusion Action
        uses: technote-space/workflow-conclusion-action@v2.0.1

      - run: echo "${{ env.WORKFLOW_CONCLUSION }}"