name: Deployment

on:
  workflow_run:
    workflows:
      - Service Build
    branches:
      - master
    types:
      - completed

jobs:
  success:
    name: Deployment of Service
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Deployment Success"

  workflow-status:
    if: always()
    name: Echo Workflow Status
    runs-on: ubuntu-latest
    needs:
      - success
    steps:
      - name: Workflow Conclusion Action
        uses: technote-space/workflow-conclusion-action@v2.0.1

      - run: echo "${{ env.WORKFLOW_CONCLUSION }}"