name: ECR Repository

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  first:
    name: Deploy ECR repository
    runs-on: ubuntu-latest
    steps:
      - run: echo "Terraform ECR deployment"