name: ECR Repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  first:
    name: Deploy ECR repository
    runs-on: ubuntu-latest
    steps:
      - run: echo "Terraform ECR deployment"

  workflow-status:
    if: always()
    name: Echo Workflow Status
    runs-on: ubuntu-latest
    needs:
      - first
    steps:
      - name: Workflow Conclusion Action
        uses: technote-space/workflow-conclusion-action@v2.0.1

      - run: echo "${{ github.event.workflow_run.conclusion == 'success' && env.WORKFLOW_CONCLUSION }}"