name: Second Workflow

on:
  workflow_run:
    workflows:
      - First Workflow
    types:
      - completed

jobs:
  first:
    name: The first job in second workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the first step, in the first job of the second workflow"