name: Second Workflow

on:
  workflow_run:
    workflows:
      - First Workflow
    types:
      - completed

jobs:
  success:
    name: First workflow success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The first workflow completed successfully and run second workflow"

  failure:
    name: First workflow failed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps: